// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.25.0";

// src/lib/mcp/tools/list-jobs.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z } from "npm:zod@^4.4.3";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_jobs_default = defineTool({
  name: "list_jobs",
  title: "List jobs",
  description: "List public jobs on WorkDay33. Optionally filter by status (active, accepted, completed) or by district. Returns up to `limit` rows (default 20, max 50).",
  inputSchema: {
    status: z.enum(["active", "accepted", "completed", "cancelled"]).optional().describe("Filter by job status."),
    district: z.string().optional().describe("Filter by district id."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, district, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = sb(ctx).from("jobs_public").select("*").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) q = q.eq("status", status);
    if (district) q = q.eq("district", district);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { jobs: data } };
  }
});

// src/lib/mcp/tools/get-job.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z2 } from "npm:zod@^4.4.3";
function sb2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_job_default = defineTool2({
  name: "get_job",
  title: "Get job",
  description: "Fetch a single job by id. Full sensitive fields visible only to owner / assigned worker / admin per RLS.",
  inputSchema: { id: z2.string().uuid().describe("Job id (uuid).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb2(ctx).from("jobs").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      const pub = await sb2(ctx).from("jobs_public").select("*").eq("id", id).maybeSingle();
      if (pub.error) return { content: [{ type: "text", text: pub.error.message }], isError: true };
      return { content: [{ type: "text", text: JSON.stringify(pub.data) }], structuredContent: { job: pub.data } };
    }
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { job: data } };
  }
});

// src/lib/mcp/tools/get-me.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.25.0";
function sb3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_me_default = defineTool3({
  name: "get_me",
  title: "Get my profile",
  description: "Return the signed-in user's WorkDay33 profile (display name, coin balance, KYC status, district).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb3(ctx).from("profiles").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { profile: data } };
  }
});

// src/lib/mcp/tools/list-my-jobs.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.25.0";
import { z as z3 } from "npm:zod@^4.4.3";
function sb4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_my_jobs_default = defineTool4({
  name: "list_my_jobs",
  title: "List my jobs",
  description: "List jobs the signed-in user posted or is working on. `role` filters between 'posted' (as employer) and 'working' (as worker).",
  inputSchema: {
    role: z3.enum(["posted", "working", "all"]).optional().describe("Which side of the job to filter on (default 'all').")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ role }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const uid = ctx.getUserId();
    const client = sb4(ctx);
    const r = role ?? "all";
    let q = client.from("jobs").select("*").order("created_at", { ascending: false }).limit(50);
    if (r === "posted") q = q.eq("user_id", uid);
    else if (r === "working") q = q.eq("worker_id", uid);
    else q = q.or(`user_id.eq.${uid},worker_id.eq.${uid}`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data) }], structuredContent: { jobs: data } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "tnaqgenjhgboqtqioida";
var mcp_default = defineMcp({
  name: "workday33-mcp",
  title: "WorkDay33",
  version: "0.1.0",
  instructions: "Tools for WorkDay33 (\u0EA7\u0EBD\u0E81\u0E94\u0EC8\u0EA7\u0E99), a Lao job marketplace. Use `list_jobs` to browse public jobs, `get_job` for full details, `get_me` for the signed-in user's profile and coin balance, and `list_my_jobs` for the user's posted/accepted jobs. All tools act as the signed-in user under RLS.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_jobs_default, get_job_default, get_me_default, list_my_jobs_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.25.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
